# Conexión con los nombres nativos de Railway
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

# Driver, opcional pero recomendable
spring.datasource.driver-class-name=org.postgresql.Driver

# El resto de tu configuración está excelente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# No olvides añadir JWT_SECRET en el panel de variables de Railway
security.jwt.secret-key=${JWT_SECRET}
security.jwt.expiration-time=3600000

# Configuración de Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true