spring.application.name=task-manager-api

# 1. URL de conexión
# localhost porque Spring corre en mi máquina, 5433 es el puerto que mapeamos en Docker
spring.datasource.url=jdbc:postgresql://localhost:5433/${DB_NAME:task-manager-db}

# 2. Credenciales
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# 3. Estrategia de JPA
# Update le dice a Hibernate que cree o actualice las tablas según tus clases Java
spring.jpa.hibernate.ddl-auto=update

# 4. Logs útiles para aprender
# Esto imprimirá en la consola del IDE los comandos SQL reales que Spring envía a Docker
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true