# URL de conexión
# Spring se conecta al puerto 5433 de mi máquina, que Docker mapea al 5432 interno de PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/${DB_NAME:task-manager-db}

# Credenciales
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Hibernate actualiza las tablas automáticamente según las entidades
spring.jpa.hibernate.ddl-auto=update

# Logs útiles para desarrollo
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true