# URL de conexion
# Spring se conecta al puerto 5433 de mi maquina, que Docker mapea al 5432 interno de PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/${DB_NAME:task-manager-db}

# Credenciales
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Hibernate actualiza las tablas automaticamente segun las entidades
spring.jpa.hibernate.ddl-auto=create

# Logs utiles para desarrollo
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
security.jwt.secret-key=00205a68bf0ba54e12e1a19d7e34eb11814ad5a8f1e4141bf56a09971c9a931c
# 1h in millisecond
security.jwt.expiration-time=3600000